table 'Data atualização'
	lineageTag: 53ab5a99-dc84-418b-8fe0-8e6399408f97

	column Texto
		dataType: string
		lineageTag: 3ec3566a-06ea-4cfd-8c03-6a06d99d4ae6
		summarizeBy: none
		sourceColumn: Texto

		annotation SummarizationSetBy = Automatic

	column Data
		dataType: string
		lineageTag: 51f7c457-99ff-4c8a-a589-30c2038f7a8f
		summarizeBy: none
		sourceColumn: Data

		annotation SummarizationSetBy = Automatic

	partition 'Data atualização' = m
		mode: import
		source =
				let
				    Fonte = GoogleSheets.Contents("https://docs.google.com/spreadsheets/d/1vAu60E1xoG7GPH5Ps5BUO1OjI3v0Iv2CM6-ifzWBW8I/edit?usp=sharing"),
				    #"Data atualização_Table" = Fonte{[name="Data atualização",ItemKind="Table"]}[Data],
				    #"Colunas Renomeadas" = Table.RenameColumns(#"Data atualização_Table",{{"Column1", "Texto"}, {"Column2", "Data"}}),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Colunas Renomeadas",{{"Data", type text}})
				in
				    #"Tipo Alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

