table Unidades
	lineageTag: 00f5922a-6a10-41d1-904b-ac4e6d6eff4d

	column CO_UNIDADE
		dataType: int64
		formatString: 0
		lineageTag: 37ad4bd2-d319-441d-9131-83ebfb99e8a9
		summarizeBy: sum
		sourceColumn: CO_UNIDADE

		annotation SummarizationSetBy = Automatic

	column NO_UNIDADE
		dataType: string
		lineageTag: 0c716ef3-36aa-401b-9f00-660d9ba6c6bc
		summarizeBy: none
		sourceColumn: NO_UNIDADE

		annotation SummarizationSetBy = Automatic

	column PAÍS
		dataType: string
		lineageTag: 4e447ff7-abc3-4e0d-9cc3-0743f1bb3981
		summarizeBy: none
		sourceColumn: PAÍS

		annotation SummarizationSetBy = Automatic

	column ESTADO
		dataType: string
		lineageTag: e88bf61a-0239-4d64-9b93-f93157e80f6c
		summarizeBy: none
		sourceColumn: ESTADO

		annotation SummarizationSetBy = Automatic

	column CIDADE
		dataType: string
		lineageTag: 6b0a6483-be02-4ce0-8f8b-d7154442be1b
		summarizeBy: none
		sourceColumn: CIDADE

		annotation SummarizationSetBy = Automatic

	column UNIDADE_SIS
		dataType: string
		lineageTag: 77ac3e85-6582-4ee2-bd50-cb8e4a1aa6c4
		summarizeBy: none
		sourceColumn: UNIDADE_SIS

		annotation SummarizationSetBy = Automatic

	partition Unidades = m
		mode: import
		source =
				let
				    Fonte = Excel.Workbook(File.Contents("D:\Users\Servidor_IFFar\Downloads\OneDrive_2025-03-07\PS 2025 _ PI\unidade.xlsx"), null, true),
				    Plan1_Sheet = Fonte{[Item="Plan1",Kind="Sheet"]}[Data],
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Plan1_Sheet, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"CO_UNIDADE", Int64.Type}, {"NO_UNIDADE", type text}, {"PAÍS", type text}, {"ESTADO", type text}, {"CIDADE", type text}, {"UNIDADE_SIS", type text}})
				in
				    #"Tipo Alterado"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

